const locations=[
 {id:1,type:'art',title:'ORIGIN SIGNAL 001',borough:'Lower East Side · Manhattan',date:'On view',x:43,y:43,desc:'A wheat-paste UFO transmission exploring the line between originality, imitation and memory.',address:'Lower East Side, New York, NY'},
 {id:2,type:'event',title:'MNC NIGHT TRANSMISSION',borough:'Koreatown · Manhattan',date:'Sep 18 · 7:00 PM',x:46,y:35,desc:'An evening meet-up connecting fashion, art, gaming and independent technology.',address:'Koreatown, New York, NY'},
 {id:3,type:'art',title:'ORIGINALITY HAS ORIGINS',borough:'Bushwick · Brooklyn',date:'On view',x:28,y:64,desc:'A street-level installation featuring the MENOCLONE UFO and the Season 2 manifesto.',address:'Bushwick, Brooklyn, NY'},
 {id:4,type:'event',title:'THRIFT AND GAMING',borough:'Long Island City · Queens',date:'Oct 03 · 2:00 PM',x:66,y:57,desc:'A community pop-up combining selected vintage, independent fashion and playable retro games.',address:'Long Island City, Queens, NY'},
 {id:5,type:'art',title:'THE CLONE ARCHIVE',borough:'Harlem · Manhattan',date:'Limited run',x:41,y:25,desc:'A temporary collection of sketches, prototypes and printed artifacts from MENOCLONE Labs.',address:'Harlem, New York, NY'},
 {id:6,type:'event',title:'SEASON 2 FIELD TEST',borough:'Williamsburg · Brooklyn',date:'Oct 24 · 12:00 PM',x:36,y:55,desc:'A public product and art preview documenting the next phase of MENOCLONE Season 2.',address:'Williamsburg, Brooklyn, NY'}
];
let filter='all',selected=1;const markers=document.querySelector('#markers'),list=document.querySelector('#locationList'),count=document.querySelector('#resultCount'),dialog=document.querySelector('#detailDialog'),content=document.querySelector('#detailContent');
function render(){const shown=locations.filter(l=>filter==='all'||l.type===filter);count.textContent=`${String(shown.length).padStart(2,'0')} SIGNALS FOUND`;markers.innerHTML=shown.map(l=>`<button aria-label="Open ${l.title}" class="marker ${l.type} ${l.id===selected?'active':''}" data-id="${l.id}" data-num="0${l.id}" style="left:${l.x}%;top:${l.y}%"></button>`).join('');list.innerHTML=shown.map(l=>`<button class="location ${l.id===selected?'active':''}" data-id="${l.id}"><span class="num">0${l.id}</span><span><h3>${l.title}</h3><p>${l.borough}<br>${l.date}</p></span><span class="type ${l.type}">${l.type.toUpperCase()}</span></button>`).join('');document.querySelectorAll('[data-id]').forEach(el=>el.onclick=()=>select(+el.dataset.id,el.classList.contains('location')))}
function select(id,open=false){selected=id;render();if(open)showDetail(id)}
function showDetail(id){const l=locations.find(v=>v.id===id);content.innerHTML=`<p class="detail-tag">SIGNAL 0${l.id} · ${l.type.toUpperCase()}</p><h2>${l.title}</h2><p>${l.desc}</p><div class="detail-meta"><div><span>LOCATION</span>${l.borough}</div><div><span>DATE / STATUS</span>${l.date}</div></div><a class="directions" target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(l.address)}">OPEN DIRECTIONS ↗</a>`;dialog.showModal()}
document.querySelectorAll('.filter').forEach(btn=>btn.onclick=()=>{document.querySelector('.filter.active').classList.remove('active');btn.classList.add('active');filter=btn.dataset.filter;render()});
document.querySelectorAll('dialog .close').forEach(btn=>btn.onclick=()=>btn.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.onclick=e=>{if(e.target===d)d.close()});render();
